In [87]:
import pandas as pd
import numpy as np

In [88]:
folder = "/home/ggobert/Downloads"
df = pd.read_csv(folder + "/datasets/dataset_train.csv")

In [89]:
df.head()

,Index,Hogwarts House,First Name,Last Name,Birthday,Best Hand,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
0,0,Ravenclaw,Tamara,Hsu,2000-03-30,Left,58384.0,-487.886086,5.727180,4.878861,4.722,272.035831,532.484226,5.231058,1039.788281,3.790369,0.715939,-232.79405,-26.89
1,1,Slytherin,Erich,Paredes,1999-10-14,Right,67239.0,-552.060507,-5.987446,5.520605,-5.612,-487.340557,367.760303,4.107170,1058.944592,7.248742,0.091674,-252.18425,-113.45
2,2,Ravenclaw,Stephany,Braun,1999-11-03,Left,23702.0,-366.076117,7.725017,3.660761,6.140,664.893521,602.585284,3.555579,1088.088348,8.728531,-0.515327,-227.34265,30.42
3,3,Gryffindor,Vesta,Mcmichael,2000-08-19,Left,32667.0,697.742809,-6.497214,-6.977428,4.026,-537.001128,523.982133,-4.809637,920.391449,0.821911,-0.014040,-256.84675,200.64
4,4,Gryffindor,Gaston,Gibbs,1998-09-27,Left,60158.0,436.775204,-7.820623,NaN,2.236,-444.262537,599.324514,-3.444377,937.434724,4.311066,-0.264070,-256.38730,157.98

In [90]:
num_col = []

for column in df.columns:
    if df[f'{column}'].apply(type).eq(float).all():
        num_col.append(column)

print(num_col)

['Arithmancy', 'Astronomy', 'Herbology', 'Defense Against the Dark Arts', 'Divination', 'Muggle Studies', 'Ancient Runes', 'History of Magic', 'Transfiguration', 'Potions', 'Care of Magical Creatures', 'Charms', 'Flying']

In [91]:
def my_count(serie):
    n = 0
    serie = serie.dropna()
    for _ in serie:
        n += 1
    return n

In [92]:
def my_min(serie):
    min = serie[0]
    for i in serie:
        if i < min:
            min = i
    return min

In [93]:
def my_max(serie):
    max = serie[0]
    for i in serie:
        if i > max:
            max = i
    return max

In [94]:
def my_mean(serie):
    serie = serie.dropna()
    size = my_count(serie)

    add_all = 0
    for i in serie:
        add_all += i
    return add_all / size

In [ ]:
def my_std(serie):

In [95]:
def my_quantile(serie, percent):
    serie = serie.dropna()
    size = my_count(serie)
    quart = percent * (size - 1)
    serie = serie.sort_values().reset_index(drop=True)

    lower = int(quart)
    upper = lower + 1
    fraction = quart - lower

    if upper < size:
        # Interpolation lineaire : on va rajouter a la valeur en dessous du pourcentage la fraction manquante : (i[26%] - i[24%]) * (25% - 24%)
        return serie.iloc[lower] + (serie.iloc[upper] - serie.iloc[lower]) * fraction
    else:
        return serie.iloc[lower]

In [ ]:
df_describe = pd.DataFrame(columns=num_col)

df_describe.loc['count'] = [my_count(df[col]) for col in num_col]
df_describe.loc['mean']  = [my_mean(df[col]) for col in num_col]
df_describe.loc['std']   = [my_std(df[col]) for col in num_col]
df_describe.loc['min']   = [my_min(df[col]) for col in num_col]
df_describe.loc['25%']   = [my_quantile(df[col], 0.25) for col in num_col]
df_describe.loc['50%']   = [my_quantile(df[col], 0.5) for col in num_col]
df_describe.loc['75%']   = [my_quantile(df[col], 0.75) for col in num_col]
df_describe.loc['max']   = [my_max(df[col]) for col in num_col]

In [97]:
df_describe

,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
count,1566.00,1568.000000,1567.000000,1569.000000,1561.000,1565.000000,1565.000000,1557.000000,1566.000000,1570.000000,1560.000000,1600.000000,1600.000
min,-24370.00,-966.740546,-10.295663,-10.162119,-8.727,-1086.496835,283.869609,-8.858993,906.627320,-4.697484,-3.313676,-261.048920,-181.470
25%,38511.50,-489.551387,-4.308182,-5.259095,3.099,-577.580096,397.511047,2.218653,1026.209993,3.646785,-0.671606,-250.652600,-41.870
50%,49013.50,260.289446,3.469012,-2.589342,4.624,-419.164294,463.918305,4.378176,1045.506996,5.874837,-0.044811,-244.867765,-2.515
75%,60811.25,524.771949,5.419183,4.904680,5.667,254.994857,597.492230,5.825242,1058.436410,8.248173,0.589919,-232.552305,50.560
max,104956.00,1016.211940,11.612895,9.667405,10.032,1092.388611,745.396220,11.889713,1098.958201,13.536762,3.056546,-225.428140,279.070

In [98]:
my_mean(df['Arithmancy'])

49634.57024265645